name: Build and Package ROS2 Iron Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t ros2-iron-builder .

    - name: Run Docker container
      run: |
        docker run --name ros2-iron-builder-container ros2-iron-builder

    - name: Create directory for deb package
      run: |
        mkdir -p ./deb-packages

    - name: Copy deb package from Docker container
      run: |
        docker cp ros2-iron-builder-container:/output/ros2_iron_packages.deb ./deb-packages/ros2_iron_packages.deb

    - name: Upload deb package
      uses: actions/upload-artifact@v2
      with:
        name: ros2-iron-packages
        path: ./deb-packages/ros2_iron_packages.deb
