name: Build ROS Deb
run-name: ${{ github.actor }} is testing out building Debs from ROS package 🚀
on:
  push:
    branches:
      - main
jobs:
  build-ros-deb:
    runs-on: ubuntu-22.04

    steps:
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tree

      - name: Build ROS Deb
        uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: iron
          REPOS_FILE: https://raw.githubusercontent.com/serhiivysotskyi/test_ros2/main/source.repos
          GITHUB_TOKEN: ${{ secrets.SERHII_GITHUB_TOKEN }}
          SQUASH_HISTORY: true

      - shell: bash
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          tree;
          deb_file=$(find . -name "*.deb");
          curl -v -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" -H "Content-Type: multipart/form-data" --data-binary "@$deb_file" "http://13.60.79.193:8080/repository/test_ros2";
